# oss-todomvc-thymeleaf-config

#logging.level.: ${LOGGING_LEVEL_:INFO}
logging:
  file: ${LOGGING_FILE:oss-todomvc-thymeleaf}.log
  level.: ${LOGGING_LEVEL_:INFO}
  level:
    jndi: ${LOGGING_LEVEL_:INFO}

  path: ${LOGGING_PATH:${user.home}/.oss/oss-todomvc-thymeleaf/logs}

app:
  type: TEMPLATE
  security:
    permited: ''
    authEntryPoint: ''
    authFailureHandler: '/login.html'
    authSucessHandler: '/index.html'
    basePath: '/auth'

debug: false


security:

  ignored: '/info,/login.html,/css/**,/js/**,/images/**,/webjars/**,/**/favicon.ico'
  user:
    name: ${SECURITY_USER_NAME:admin}
    password: ${SECURITY_USER_PASSWORD:admin_pass}
    role: ADMIN

server:
  error:
    includeStacktrace: ALWAYS   # 记录 trace
  port: ${SERVER_PORT:8083}

spring:
  #application.name: oss-todomvc-thymeleaf # in bootstrap.yml
  cloud.config:
    password: '{cipher}AQAp06zZZdziujcJMH2OQyQrQIaLzYa5NC39K3mTtlWRfB94qsXGwVoOKUk20sGYZsw84OWbc9uF4BGqoPhnEaPmIniSB021BlbpwFaVuqqKmnSgPUmuL6GTw3Qb/xDVILkIvbfjvC7JbSyjMgJ4zDdRbxvVN9V66ndcEDI4p6VRDglPHyl1kTwSkT7798XRlmFAUWmOXg/lu+gQLUajMjHS96PtywrqgfjUmxoM323BZoT2PEAWoGorbREKETwwj2wOuq6+hsQ/by8hez+s3tW9gxKFJoD9BWP+qDQFIjkgt9kUeJU5WddSjD+G6At2Lkke7LTXBwfY3N8dns+2nhg6xXk9v9Wm8FR18hfvG+UoCliShwiHB1rgKv0cTa4cwQc='
    common-config:
      enabled: true
      application: common

spring.datasource:
  continue-on-error: false 
  initialize: false # Populate the database using 'data.sql'.
  jmx-enabled: false # Enable JMX support (if provided by the underlying pool).
  maximum-pool-size: 10
  minimum-idle: 5
  name: dataSource
  test-while-idle: true
  time-between-eviction-runs-millis: 1
  validation-query: 'SELECT 1'
  type: 'com.zaxxer.hikari.HikariDataSource'
  driver-class-name: 'org.h2.Driver'
  url: 'jdbc:h2:~/.oss/oss-todomvc-thymeleaf/h2' #'jdbc:h2:mem:mydb'
  
---
spring:
  profiles: default

---
spring:
  profiles: development.env

app:
  security:
    enabled: true
    defaultTestUser: user1
    loginPage: '/login'
    authSucessHandler: '/index.html' # 登录成功跳转页面

---
spring:
  profiles: ut.env

---
spring:
  profiles: it.env

---
spring:
  profiles: staging.env

---
spring:
  profiles: production.env

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql.local:3306/oss-todomvc-thymeleaf?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: root

spring.h2.console.enabled: false

spring.jpa:
  database: MYSQL
  database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
  generate-ddl: false
  hibernate.ddl-auto: none
  show-sql: false
